<?php

//application details
$apps[$x]['name'] = "OpenID Connect";
$apps[$x]['uuid'] = "c6a00005-7967-4a91-bb17-f8f713e1c5d5";
$apps[$x]['category'] = "";
$apps[$x]['subcategory'] = "";
$apps[$x]['version'] = "1.1";
$apps[$x]['license'] = "Mozilla Public License 1.1";
$apps[$x]['url'] = "http://www.fusionpbx.com";
$apps[$x]['description']['en-us'] = "OpenID Connect plugin";
$apps[$x]['description']['en-gb'] = "OpenID Connect plugin";
$apps[$x]['description']['ar-eg'] = "";
$apps[$x]['description']['de-at'] = "";
$apps[$x]['description']['de-ch'] = "";
$apps[$x]['description']['de-de'] = "";
$apps[$x]['description']['el-gr'] = "";
$apps[$x]['description']['es-cl'] = "";
$apps[$x]['description']['es-mx'] = "";
$apps[$x]['description']['fr-ca'] = "";
$apps[$x]['description']['fr-fr'] = "";
$apps[$x]['description']['he-il'] = "";
$apps[$x]['description']['it-it'] = "";
$apps[$x]['description']['nl-nl'] = "";
$apps[$x]['description']['pl-pl'] = "";
$apps[$x]['description']['pt-br'] = "";
$apps[$x]['description']['pt-pt'] = "";
$apps[$x]['description']['ro-ro'] = "";
$apps[$x]['description']['ru-ru'] = "";
$apps[$x]['description']['sv-se'] = "";
$apps[$x]['description']['uk-ua'] = "";

//default settings
$y=0;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a9cb0998-4b33-4c19-a885-d198fde2d205";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_client_id";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Client ID set in console.cloud.google.com project";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "64268416-eaa9-455e-8e21-6d64f3c20e7c";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_client_secret";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Client secret set in console.cloud.google.com project";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "607b7859-221c-4340-a8d1-8659d290d662";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "enabled";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enables the OpenID Connect authentication modules";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ceb26453-0c92-484b-8f48-b5858cf821bc";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_image";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "/var/www/fusionpbx/app/open_id/resources/images/google/web_light_sq_SI@1x.png";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Google image to use for the login banner";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d2329083-d3b1-40b3-b1ef-f2ec9c1bc6e9";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_metadata_domain";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "accounts.google.com";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Meta domain for the google OIDC discovery";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "71bd5ca5-90fe-4cc3-9d79-6737d46db95f";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_metadata_path";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "/.well-known/openid-configuration";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Meta path for the google OIDC discovery";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2548fddc-30dc-435c-8a4f-b5ec69db1219";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_redirect_uri";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = 'https://{$domain_name}/app/open_id/open_id.php?action={$plugin}';
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Redirect URI set in console.cloud.google.com project";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "ac194360-a2a0-49a2-ab73-d6a3d8cb03ce";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "methods";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "array";
$apps[$x]['default_settings'][$y]['default_setting_order'] = "000";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "open_id_google";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "OpenID Connect Authenticator for Google";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "142ab862-22d9-44c0-be47-101af4fd9819";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "methods";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "array";
$apps[$x]['default_settings'][$y]['default_setting_order'] = "010";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "open_id_okta";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "OpenID Connect Authenticator for OKTA";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f6414e3a-9113-4c5f-8076-b0f6256989aa";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "suppress_errors";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "boolean";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Suppress errors detected when trying to use OpenID Connect. This is helpful when trying to set up the client";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7ebf4bac-d91f-4aea-9614-1a690f3700a5";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "google_username_mapping";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "email=user_email";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Map the Google OpenID Connect email field to the user_email in the users table column";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "40a2a453-6ff4-402c-a80d-6065d220edd9";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "okta_username_mapping";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "username=user_email";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Map the OKTA OpenID Connect email field to the user_email in the users table column";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4d0c8ace-c634-4aa0-8922-0c49e95b3c93";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "okta_redirect_uri";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = 'https://{$domain_name}/app/open_id/open_id.php?action={$plugin}';
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set this value to the same value that is in the OKTA Login section of the administration application panel";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6fd85364-e99a-41a0-bf11-38a861cf2bb6";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "okta_client_id";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set this value to the same value that is in the OKTA Login section of the administration application panel";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "55ff8747-cd7a-4074-a91f-6a9342a13037";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "okta_client_secret";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set this value to the same value that is in the OKTA Login section of the administration application panel";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "3e30b104-38fa-4c78-b415-9663747b6775";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "okta_metadata_domain";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set this value to the same value that is in the OKTA Login section of the administration application panel";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4dd8e974-edc4-48a6-94ae-841ac1485106";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "okta_metadata_server";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "default";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Set this value to the same value that is in the OKTA Login section of the administration application panel";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "cff507d4-151b-4ef3-8fed-43a6310b3cef";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "methods";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "array";
$apps[$x]['default_settings'][$y]['default_setting_order'] = "020";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "open_id_microsoft";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "OpenID Connect Authenticator for Microsoft (Entra ID / Azure AD)";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "543d0da8-d866-4b17-a9a9-3b939f5996d9";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_client_id";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Application (client) ID from the Microsoft Entra app registration";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "992acf65-15ef-42b4-8e67-c648754a5455";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_client_secret";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Client secret value from the Microsoft Entra app registration";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "bcf3af86-011c-4712-8cef-601ffed35168";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_redirect_uri";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = 'https://{$domain_name}/app/open_id/open_id.php?action={$plugin}';
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Redirect URI registered in the Microsoft Entra app registration";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "f91e1125-2d7b-4caa-ba71-b01ae66abc20";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_metadata_domain";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "login.microsoftonline.com";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Meta domain for the Microsoft OIDC discovery";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "814a5dbb-a2eb-41c4-bbbd-4b1ea9b286d6";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_metadata_path";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "/common/v2.0/.well-known/openid-configuration";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Meta path for the Microsoft OIDC discovery. Replace 'common' with a tenant ID to restrict to a single organization";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2dabbafc-46d7-4e17-a75a-021636611ab9";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_username_mapping";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "preferred_username=user_email";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Map the Microsoft OpenID Connect claim to the user_email column in the users table";
$y++;
$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "040c28c8-96ba-44db-a67c-05fa816cd28a";
$apps[$x]['default_settings'][$y]['default_setting_category'] = "open_id";
$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "microsoft_image";
$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
$apps[$x]['default_settings'][$y]['default_setting_description'] = "Optional path to a Microsoft image for the login banner. When empty a branded button is rendered";
